package com.dcits.busi.lkymop.page;

import com.dcits.yi.ui.element.BasePage;
import com.dcits.yi.ui.element.PageElement;

/**
 * This PageModel is generated by MasterYIUITest
 *
 */

public class UserPage extends BasePage {
	
	public PageElement userlist;	
	public PageElement userquerybypage;
	public PageElement nameselect;
	public PageElement add;

	/**
	 * 员工查询
	 */
	public void usersend(String username)
	{
		this.userlist.click();
		this.userquerybypage.click();
		this.nameselect.sendKeys(username);
		screenshot();

	}
	
}